services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/go/src/api
      - ./database:/go/src/database
      - ./docs:/go/src/docs
    # command: ./app_launch.sh
    ports:
      - 8081:8081
    environment:
      MYSQL_DATABASE: echodev
      MYSQL_HOST: mysql_host
      MYSQL_USER: echo
      MYSQL_PASSWORD: echo
    networks:
      - echo
    links:
      - db
    tty: true
  
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: echodev
      MYSQL_USER: echo
      MYSQL_PASSWORD: echo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/db:/db
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - echo

networks:
  echo:
    driver: bridge
    